// <auto-generated />
using System;
using Microondas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microondas.Migrations.Migrations
{
    [DbContext(typeof(MicroondasDbContext))]
    [Migration("20260408030359_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microondas.Domain.Programs.HeatingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HeatingPrograms", (string)null);
                });

            modelBuilder.Entity("Microondas.Domain.Programs.HeatingProgram", b =>
                {
                    b.OwnsOne("Microondas.Domain.Heating.ValueObjects.HeatingCharacter", "Character", b1 =>
                        {
                            b1.Property<Guid>("HeatingProgramId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1)
                                .HasColumnType("nvarchar(1)")
                                .HasColumnName("HeatingChar");

                            b1.HasKey("HeatingProgramId");

                            b1.ToTable("HeatingPrograms");

                            b1.WithOwner()
                                .HasForeignKey("HeatingProgramId");
                        });

                    b.OwnsOne("Microondas.Domain.Heating.ValueObjects.HeatingTime", "Time", b1 =>
                        {
                            b1.Property<Guid>("HeatingProgramId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("TotalSeconds")
                                .HasColumnType("int")
                                .HasColumnName("TimeInSeconds");

                            b1.HasKey("HeatingProgramId");

                            b1.ToTable("HeatingPrograms");

                            b1.WithOwner()
                                .HasForeignKey("HeatingProgramId");
                        });

                    b.OwnsOne("Microondas.Domain.Heating.ValueObjects.PowerLevel", "Power", b1 =>
                        {
                            b1.Property<Guid>("HeatingProgramId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Power");

                            b1.HasKey("HeatingProgramId");

                            b1.ToTable("HeatingPrograms");

                            b1.WithOwner()
                                .HasForeignKey("HeatingProgramId");
                        });

                    b.OwnsOne("Microondas.Domain.Programs.ValueObjects.FoodDescription", "Food", b1 =>
                        {
                            b1.Property<Guid>("HeatingProgramId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Food");

                            b1.HasKey("HeatingProgramId");

                            b1.ToTable("HeatingPrograms");

                            b1.WithOwner()
                                .HasForeignKey("HeatingProgramId");
                        });

                    b.OwnsOne("Microondas.Domain.Programs.ValueObjects.InstructionText", "Instructions", b1 =>
                        {
                            b1.Property<Guid>("HeatingProgramId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Instructions");

                            b1.HasKey("HeatingProgramId");

                            b1.ToTable("HeatingPrograms");

                            b1.WithOwner()
                                .HasForeignKey("HeatingProgramId");
                        });

                    b.OwnsOne("Microondas.Domain.Programs.ValueObjects.ProgramName", "Name", b1 =>
                        {
                            b1.Property<Guid>("HeatingProgramId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Name");

                            b1.HasKey("HeatingProgramId");

                            b1.ToTable("HeatingPrograms");

                            b1.WithOwner()
                                .HasForeignKey("HeatingProgramId");
                        });

                    b.Navigation("Character")
                        .IsRequired();

                    b.Navigation("Food")
                        .IsRequired();

                    b.Navigation("Instructions")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Power")
                        .IsRequired();

                    b.Navigation("Time")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
